/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.1 */
/* Tue Mar 09 16:14:07 2021 */

/* parameterized module instance */
aud_buffer __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ), .AlmostFull( ));
