/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* Fri Jan 08 13:27:57 2021 */

/* parameterized module instance */
cam_in_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .RCNT( ), .Empty( ), .Full( ), 
    .AlmostEmpty( ));
