/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n slfifo_fifo -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type ebfifo -depth 512 -width 64 -rwidth 32 -regout -no_enable -sync_reset -pe 10 -pe2 11 -pf 488 -rfill -fill -fdc F:/cypress_prj/FTP/HDMI_RX_FPGA_design_FULLHD/PAR/ddr_ip/slfifo_fifo/slfifo_fifo.fdc  */
/* Fri Jan 08 13:28:29 2021 */


`timescale 1 ns / 1 ps
module slfifo_fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, WCNT, RCNT, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [63:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [31:0] Q;
    output wire [9:0] WCNT;
    output wire [10:0] RCNT;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire invout_1;
    wire invout_0;
    wire w_g2b_xor_cluster_1;
    wire rcount_w0;
    wire r_g2b_xor_cluster_2;
    wire r_g2b_xor_cluster_1;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire w_gdata_7;
    wire w_gdata_8;
    wire wptr_9;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire r_gdata_7;
    wire r_gdata_8;
    wire r_gdata_9;
    wire rptr_10;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire w_gcount_8;
    wire w_gcount_9;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire r_gcount_8;
    wire r_gcount_9;
    wire r_gcount_10;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire w_gcount_r28;
    wire w_gcount_r8;
    wire w_gcount_r29;
    wire w_gcount_r9;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire r_gcount_w28;
    wire r_gcount_w8;
    wire r_gcount_w29;
    wire r_gcount_w9;
    wire r_gcount_w210;
    wire r_gcount_w10;
    wire empty_i;
    wire full_i;
    wire ae;
    wire rRst;
    wire ae_d;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co2;
    wire iwcount_8;
    wire iwcount_9;
    wire co4;
    wire co3;
    wire wcount_9;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co2_1;
    wire ircount_8;
    wire ircount_9;
    wire co3_1;
    wire ircount_10;
    wire co5;
    wire co4_1;
    wire rcount_10;
    wire wfill_sub_0;
    wire wptr_0;
    wire precin;
    wire wfill_sub_1;
    wire wfill_sub_2;
    wire wptr_2;
    wire wptr_1;
    wire co0_2;
    wire wfill_sub_3;
    wire wfill_sub_4;
    wire wptr_4;
    wire wptr_3;
    wire co1_2;
    wire wfill_sub_5;
    wire wfill_sub_6;
    wire wptr_6;
    wire wptr_5;
    wire co2_2;
    wire wfill_sub_7;
    wire wfill_sub_8;
    wire wptr_8;
    wire wptr_7;
    wire co3_2;
    wire wfill_sub_9;
    wire wfill_sub_msb;
    wire co4_2;
    wire rfill_sub_0;
    wire rptr_0;
    wire precin_1;
    wire rfill_sub_1;
    wire rfill_sub_2;
    wire rptr_2;
    wire rptr_1;
    wire co0_3;
    wire rfill_sub_3;
    wire rfill_sub_4;
    wire rptr_4;
    wire rptr_3;
    wire co1_3;
    wire rfill_sub_5;
    wire rfill_sub_6;
    wire rptr_6;
    wire rptr_5;
    wire co2_3;
    wire rfill_sub_7;
    wire rfill_sub_8;
    wire rptr_8;
    wire rptr_7;
    wire co3_3;
    wire rfill_sub_9;
    wire rfill_sub_10;
    wire rptr_9;
    wire rfill_sub_msb;
    wire co4_3;
    wire co5_1d;
    wire co5_1;
    wire cmp_ci;
    wire rcount_0;
    wire rcount_1;
    wire co0_4;
    wire rcount_2;
    wire rcount_3;
    wire co1_4;
    wire rcount_4;
    wire rcount_5;
    wire co2_4;
    wire rcount_6;
    wire rcount_7;
    wire co3_4;
    wire rcount_8;
    wire rcount_9;
    wire co4_4;
    wire empty_cmp_clr;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire cmp_ci_1;
    wire wcount_0;
    wire wcount_1;
    wire co0_5;
    wire wcount_2;
    wire wcount_3;
    wire co1_5;
    wire wcount_4;
    wire wcount_5;
    wire co2_5;
    wire wcount_6;
    wire wcount_7;
    wire co3_5;
    wire full_cmp_clr;
    wire wcount_8;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire iae_setcount_0;
    wire iae_setcount_1;
    wire ae_set_ctr_ci;
    wire iae_setcount_2;
    wire iae_setcount_3;
    wire co0_6;
    wire iae_setcount_4;
    wire iae_setcount_5;
    wire co1_6;
    wire iae_setcount_6;
    wire iae_setcount_7;
    wire co2_6;
    wire iae_setcount_8;
    wire iae_setcount_9;
    wire co3_6;
    wire iae_setcount_10;
    wire co5_2;
    wire co4_5;
    wire ae_setcount_10;
    wire cmp_ci_2;
    wire ae_setcount_0;
    wire ae_setcount_1;
    wire co0_7;
    wire ae_setcount_2;
    wire ae_setcount_3;
    wire co1_7;
    wire ae_setcount_4;
    wire ae_setcount_5;
    wire co2_7;
    wire ae_setcount_6;
    wire ae_setcount_7;
    wire co3_7;
    wire ae_setcount_8;
    wire ae_setcount_9;
    wire co4_6;
    wire ae_set_cmp_clr;
    wire ae_set_cmp_set;
    wire ae_set_d;
    wire ae_set_d_c;
    wire iae_clrcount_0;
    wire iae_clrcount_1;
    wire ae_clr_ctr_ci;
    wire iae_clrcount_2;
    wire iae_clrcount_3;
    wire co0_8;
    wire iae_clrcount_4;
    wire iae_clrcount_5;
    wire co1_8;
    wire iae_clrcount_6;
    wire iae_clrcount_7;
    wire co2_8;
    wire iae_clrcount_8;
    wire iae_clrcount_9;
    wire co3_8;
    wire iae_clrcount_10;
    wire co5_3;
    wire co4_7;
    wire ae_clrcount_10;
    wire rden_i;
    wire cmp_ci_3;
    wire wcount_r0;
    wire ae_clrcount_0;
    wire ae_clrcount_1;
    wire co0_9;
    wire wcount_r1;
    wire wcount_r2;
    wire ae_clrcount_2;
    wire ae_clrcount_3;
    wire co1_9;
    wire wcount_r3;
    wire wcount_r4;
    wire ae_clrcount_4;
    wire ae_clrcount_5;
    wire co2_9;
    wire wcount_r5;
    wire w_g2b_xor_cluster_0;
    wire ae_clrcount_6;
    wire ae_clrcount_7;
    wire co3_9;
    wire wcount_r7;
    wire wcount_r8;
    wire ae_clrcount_8;
    wire ae_clrcount_9;
    wire co4_8;
    wire ae_clr_cmp_clr;
    wire ae_clr_cmp_set;
    wire ae_clr_d;
    wire ae_clr_d_c;
    wire iaf_setcount_0;
    wire iaf_setcount_1;
    wire af_set_ctr_ci;
    wire iaf_setcount_2;
    wire iaf_setcount_3;
    wire co0_10;
    wire iaf_setcount_4;
    wire iaf_setcount_5;
    wire co1_10;
    wire iaf_setcount_6;
    wire iaf_setcount_7;
    wire co2_10;
    wire iaf_setcount_8;
    wire iaf_setcount_9;
    wire co4_9;
    wire co3_10;
    wire af_setcount_9;
    wire wren_i;
    wire cmp_ci_4;
    wire rcount_w1;
    wire rcount_w2;
    wire af_setcount_0;
    wire af_setcount_1;
    wire co0_11;
    wire rcount_w3;
    wire rcount_w4;
    wire af_setcount_2;
    wire af_setcount_3;
    wire co1_11;
    wire rcount_w5;
    wire rcount_w6;
    wire af_setcount_4;
    wire af_setcount_5;
    wire co2_11;
    wire r_g2b_xor_cluster_0;
    wire rcount_w8;
    wire af_setcount_6;
    wire af_setcount_7;
    wire co3_11;
    wire rcount_w9;
    wire af_set_cmp_clr;
    wire af_setcount_8;
    wire af_set_cmp_set;
    wire af_set;
    wire scuba_vhi;
    wire scuba_vlo;
    wire af_set_c;

    AND2 AND2_t23 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t22 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t21 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t20 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t19 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t18 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t17 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t16 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t15 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t14 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t13 (.A(wcount_7), .B(wcount_8), .Z(w_gdata_7));

    XOR2 XOR2_t12 (.A(wcount_8), .B(wcount_9), .Z(w_gdata_8));

    XOR2 XOR2_t11 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t10 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t9 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t8 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t7 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t6 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t5 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    XOR2 XOR2_t4 (.A(rcount_7), .B(rcount_8), .Z(r_gdata_7));

    XOR2 XOR2_t3 (.A(rcount_8), .B(rcount_9), .Z(r_gdata_8));

    XOR2 XOR2_t2 (.A(rcount_9), .B(rcount_10), .Z(r_gdata_9));

    defparam LUT4_32.initval =  16'h6996 ;
    ROM16X1A LUT4_32 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(w_gcount_r28), 
        .AD0(w_gcount_r29), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_31.initval =  16'h6996 ;
    ROM16X1A LUT4_31 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(w_gcount_r25), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_30.initval =  16'h6996 ;
    ROM16X1A LUT4_30 (.AD3(w_gcount_r28), .AD2(w_gcount_r29), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r8));

    defparam LUT4_29.initval =  16'h6996 ;
    ROM16X1A LUT4_29 (.AD3(w_gcount_r27), .AD2(w_gcount_r28), .AD1(w_gcount_r29), 
        .AD0(scuba_vlo), .DO0(wcount_r7));

    defparam LUT4_28.initval =  16'h6996 ;
    ROM16X1A LUT4_28 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(w_gcount_r27), 
        .AD0(wcount_r8), .DO0(wcount_r5));

    defparam LUT4_27.initval =  16'h6996 ;
    ROM16X1A LUT4_27 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(w_gcount_r26), 
        .AD0(wcount_r7), .DO0(wcount_r4));

    defparam LUT4_26.initval =  16'h6996 ;
    ROM16X1A LUT4_26 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r3));

    defparam LUT4_25.initval =  16'h6996 ;
    ROM16X1A LUT4_25 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r2));

    defparam LUT4_24.initval =  16'h6996 ;
    ROM16X1A LUT4_24 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r21), .AD0(scuba_vlo), .DO0(wcount_r1));

    defparam LUT4_23.initval =  16'h6996 ;
    ROM16X1A LUT4_23 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r20), .AD0(w_gcount_r21), .DO0(wcount_r0));

    defparam LUT4_22.initval =  16'h6996 ;
    ROM16X1A LUT4_22 (.AD3(r_gcount_w27), .AD2(r_gcount_w28), .AD1(r_gcount_w29), 
        .AD0(r_gcount_w210), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_21.initval =  16'h6996 ;
    ROM16X1A LUT4_21 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(r_gcount_w26), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_20.initval =  16'h6996 ;
    ROM16X1A LUT4_20 (.AD3(r_gcount_w29), .AD2(r_gcount_w210), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w9));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(r_gcount_w28), .AD2(r_gcount_w29), .AD1(r_gcount_w210), 
        .AD0(scuba_vlo), .DO0(rcount_w8));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(r_gcount_w28), 
        .AD0(rcount_w9), .DO0(rcount_w6));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27), 
        .AD0(rcount_w8), .DO0(rcount_w5));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w4));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w3));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w22), .AD0(scuba_vlo), .DO0(rcount_w2));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w21), .AD0(r_gcount_w22), .DO0(rcount_w1));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22), 
        .AD0(scuba_vlo), .DO0(r_g2b_xor_cluster_2));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(rcount_w0));

    XOR2 XOR2_t1 (.A(wptr_9), .B(r_gcount_w210), .Z(wfill_sub_msb));

    XOR2 XOR2_t0 (.A(w_gcount_r29), .B(rptr_10), .Z(rfill_sub_msb));

    defparam LUT4_10.initval =  16'h0410 ;
    ROM16X1A LUT4_10 (.AD3(rptr_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(scuba_vlo), .DO0(empty_cmp_set));

    defparam LUT4_9.initval =  16'h1004 ;
    ROM16X1A LUT4_9 (.AD3(rptr_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(scuba_vlo), .DO0(empty_cmp_clr));

    defparam LUT4_8.initval =  16'h0140 ;
    ROM16X1A LUT4_8 (.AD3(wptr_9), .AD2(wcount_9), .AD1(r_gcount_w210), 
        .AD0(scuba_vlo), .DO0(full_cmp_set));

    defparam LUT4_7.initval =  16'h4001 ;
    ROM16X1A LUT4_7 (.AD3(wptr_9), .AD2(wcount_9), .AD1(r_gcount_w210), 
        .AD0(scuba_vlo), .DO0(full_cmp_clr));

    defparam LUT4_6.initval =  16'h13c8 ;
    ROM16X1A LUT4_6 (.AD3(ae_setcount_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(rptr_10), .DO0(ae_set_cmp_set));

    defparam LUT4_5.initval =  16'h2004 ;
    ROM16X1A LUT4_5 (.AD3(ae_setcount_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(rptr_10), .DO0(ae_set_cmp_clr));

    defparam LUT4_4.initval =  16'h13c8 ;
    ROM16X1A LUT4_4 (.AD3(ae_clrcount_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(rptr_10), .DO0(ae_clr_cmp_set));

    defparam LUT4_3.initval =  16'h2004 ;
    ROM16X1A LUT4_3 (.AD3(ae_clrcount_10), .AD2(rcount_10), .AD1(w_gcount_r29), 
        .AD0(rptr_10), .DO0(ae_clr_cmp_clr));

    defparam LUT4_2.initval =  16'h4450 ;
    ROM16X1A LUT4_2 (.AD3(ae), .AD2(ae_set_d), .AD1(ae_clr_d), .AD0(scuba_vlo), 
        .DO0(ae_d));

    defparam LUT4_1.initval =  16'h4c32 ;
    ROM16X1A LUT4_1 (.AD3(af_setcount_9), .AD2(wcount_9), .AD1(r_gcount_w210), 
        .AD0(wptr_9), .DO0(af_set_cmp_set));

    defparam LUT4_0.initval =  16'h8001 ;
    ROM16X1A LUT4_0 (.AD3(af_setcount_9), .AD2(wcount_9), .AD1(r_gcount_w210), 
        .AD0(wptr_9), .DO0(af_set_cmp_clr));

    defparam pdp_ram_0_0_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_1.CSDECODE_R = "0b001" ;
    defparam pdp_ram_0_0_1.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_0_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_1.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_0_1.REGMODE = "OUTREG" ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_W = 36 ;
    PDPW16KD pdp_ram_0_0_1 (.DI35(Data[49]), .DI34(Data[48]), .DI33(Data[47]), 
        .DI32(Data[46]), .DI31(Data[45]), .DI30(Data[44]), .DI29(Data[43]), 
        .DI28(Data[42]), .DI27(Data[41]), .DI26(Data[40]), .DI25(Data[39]), 
        .DI24(Data[38]), .DI23(Data[37]), .DI22(Data[36]), .DI21(Data[35]), 
        .DI20(Data[34]), .DI19(Data[33]), .DI18(Data[32]), .DI17(Data[17]), 
        .DI16(Data[16]), .DI15(Data[15]), .DI14(Data[14]), .DI13(Data[13]), 
        .DI12(Data[12]), .DI11(Data[11]), .DI10(Data[10]), .DI9(Data[9]), 
        .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), .DI5(Data[5]), .DI4(Data[4]), 
        .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), .DI0(Data[0]), .ADW8(wptr_8), 
        .ADW7(wptr_7), .ADW6(wptr_6), .ADW5(wptr_5), .ADW4(wptr_4), .ADW3(wptr_3), 
        .ADW2(wptr_2), .ADW1(wptr_1), .ADW0(wptr_0), .BE3(scuba_vhi), .BE2(scuba_vhi), 
        .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(scuba_vhi), .ADR13(rptr_9), 
        .ADR12(rptr_8), .ADR11(rptr_7), .ADR10(rptr_6), .ADR9(rptr_5), .ADR8(rptr_4), 
        .ADR7(rptr_3), .ADR6(rptr_2), .ADR5(rptr_1), .ADR4(rptr_0), .ADR3(scuba_vlo), 
        .ADR2(scuba_vlo), .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(scuba_vhi), 
        .OCER(scuba_vhi), .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), 
        .CSR0(rden_i), .RST(Reset), .DO35(), .DO34(), .DO33(), .DO32(), 
        .DO31(), .DO30(), .DO29(), .DO28(), .DO27(), .DO26(), .DO25(), .DO24(), 
        .DO23(), .DO22(), .DO21(), .DO20(), .DO19(), .DO18(), .DO17(Q[17]), 
        .DO16(Q[16]), .DO15(Q[15]), .DO14(Q[14]), .DO13(Q[13]), .DO12(Q[12]), 
        .DO11(Q[11]), .DO10(Q[10]), .DO9(Q[9]), .DO8(Q[8]), .DO7(Q[7]), 
        .DO6(Q[6]), .DO5(Q[5]), .DO4(Q[4]), .DO3(Q[3]), .DO2(Q[2]), .DO1(Q[1]), 
        .DO0(Q[0]))
             /* synthesis MEM_LPC_FILE="slfifo_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_0.CSDECODE_R = "0b001" ;
    defparam pdp_ram_0_1_0.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_1_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_0.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_1_0.REGMODE = "OUTREG" ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_W = 36 ;
    PDPW16KD pdp_ram_0_1_0 (.DI35(scuba_vlo), .DI34(scuba_vlo), .DI33(scuba_vlo), 
        .DI32(scuba_vlo), .DI31(Data[63]), .DI30(Data[62]), .DI29(Data[61]), 
        .DI28(Data[60]), .DI27(Data[59]), .DI26(Data[58]), .DI25(Data[57]), 
        .DI24(Data[56]), .DI23(Data[55]), .DI22(Data[54]), .DI21(Data[53]), 
        .DI20(Data[52]), .DI19(Data[51]), .DI18(Data[50]), .DI17(scuba_vlo), 
        .DI16(scuba_vlo), .DI15(scuba_vlo), .DI14(scuba_vlo), .DI13(Data[31]), 
        .DI12(Data[30]), .DI11(Data[29]), .DI10(Data[28]), .DI9(Data[27]), 
        .DI8(Data[26]), .DI7(Data[25]), .DI6(Data[24]), .DI5(Data[23]), 
        .DI4(Data[22]), .DI3(Data[21]), .DI2(Data[20]), .DI1(Data[19]), 
        .DI0(Data[18]), .ADW8(wptr_8), .ADW7(wptr_7), .ADW6(wptr_6), .ADW5(wptr_5), 
        .ADW4(wptr_4), .ADW3(wptr_3), .ADW2(wptr_2), .ADW1(wptr_1), .ADW0(wptr_0), 
        .BE3(scuba_vhi), .BE2(scuba_vhi), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(wren_i), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(scuba_vhi), .ADR13(rptr_9), .ADR12(rptr_8), .ADR11(rptr_7), 
        .ADR10(rptr_6), .ADR9(rptr_5), .ADR8(rptr_4), .ADR7(rptr_3), .ADR6(rptr_2), 
        .ADR5(rptr_1), .ADR4(rptr_0), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(scuba_vhi), .OCER(scuba_vhi), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(rden_i), 
        .RST(Reset), .DO35(), .DO34(), .DO33(), .DO32(), .DO31(), .DO30(), 
        .DO29(), .DO28(), .DO27(), .DO26(), .DO25(), .DO24(), .DO23(), .DO22(), 
        .DO21(), .DO20(), .DO19(), .DO18(), .DO17(), .DO16(), .DO15(), .DO14(), 
        .DO13(Q[31]), .DO12(Q[30]), .DO11(Q[29]), .DO10(Q[28]), .DO9(Q[27]), 
        .DO8(Q[26]), .DO7(Q[25]), .DO6(Q[24]), .DO5(Q[23]), .DO4(Q[22]), 
        .DO3(Q[21]), .DO2(Q[20]), .DO1(Q[19]), .DO0(Q[18]))
             /* synthesis MEM_LPC_FILE="slfifo_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_161 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_160 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_159 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_158 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_157 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_156 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_155 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_154 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_153 (.D(iwcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_152 (.D(iwcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_151 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_150 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_149 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_148 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_147 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_146 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_145 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_144 (.D(w_gdata_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_143 (.D(w_gdata_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_142 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_141 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_140 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_139 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_138 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_137 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_136 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_135 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_134 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_133 (.D(wcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_132 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_131 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_130 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_129 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_128 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_127 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_126 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_125 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_124 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_123 (.D(ircount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_122 (.D(ircount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_121 (.D(ircount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_120 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_119 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_118 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_117 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_116 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_115 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_114 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_113 (.D(r_gdata_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_112 (.D(r_gdata_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_111 (.D(r_gdata_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_110 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_109 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_108 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_107 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_106 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_105 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_104 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_103 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_102 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_101 (.D(rcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_98 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_97 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_96 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_95 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_94 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_93 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_92 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_91 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_90 (.D(w_gcount_8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_89 (.D(w_gcount_9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_88 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_87 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_86 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_85 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_84 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_83 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_82 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_81 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_80 (.D(r_gcount_8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_79 (.D(r_gcount_9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_78 (.D(r_gcount_10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_77 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_76 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_75 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_74 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_73 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_72 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_71 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_70 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_69 (.D(w_gcount_r8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_68 (.D(w_gcount_r9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_67 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_66 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_65 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_64 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_63 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_62 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_61 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_60 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_59 (.D(r_gcount_w8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_58 (.D(r_gcount_w9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_57 (.D(r_gcount_w10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_56 (.D(wfill_sub_0), .CK(WrClock), .CD(Reset), .Q(WCNT[0]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_55 (.D(wfill_sub_1), .CK(WrClock), .CD(Reset), .Q(WCNT[1]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_54 (.D(wfill_sub_2), .CK(WrClock), .CD(Reset), .Q(WCNT[2]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_53 (.D(wfill_sub_3), .CK(WrClock), .CD(Reset), .Q(WCNT[3]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_52 (.D(wfill_sub_4), .CK(WrClock), .CD(Reset), .Q(WCNT[4]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_51 (.D(wfill_sub_5), .CK(WrClock), .CD(Reset), .Q(WCNT[5]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_50 (.D(wfill_sub_6), .CK(WrClock), .CD(Reset), .Q(WCNT[6]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_49 (.D(wfill_sub_7), .CK(WrClock), .CD(Reset), .Q(WCNT[7]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_48 (.D(wfill_sub_8), .CK(WrClock), .CD(Reset), .Q(WCNT[8]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_47 (.D(wfill_sub_9), .CK(WrClock), .CD(Reset), .Q(WCNT[9]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_46 (.D(rfill_sub_0), .CK(RdClock), .CD(rRst), .Q(RCNT[0]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(rfill_sub_1), .CK(RdClock), .CD(rRst), .Q(RCNT[1]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(rfill_sub_2), .CK(RdClock), .CD(rRst), .Q(RCNT[2]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(rfill_sub_3), .CK(RdClock), .CD(rRst), .Q(RCNT[3]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(rfill_sub_4), .CK(RdClock), .CD(rRst), .Q(RCNT[4]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(rfill_sub_5), .CK(RdClock), .CD(rRst), .Q(RCNT[5]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(rfill_sub_6), .CK(RdClock), .CD(rRst), .Q(RCNT[6]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(rfill_sub_7), .CK(RdClock), .CD(rRst), .Q(RCNT[7]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(rfill_sub_8), .CK(RdClock), .CD(rRst), .Q(RCNT[8]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(rfill_sub_9), .CK(RdClock), .CD(rRst), .Q(RCNT[9]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(rfill_sub_10), .CK(RdClock), .CD(rRst), .Q(RCNT[10]))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_35 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_33 (.D(iae_setcount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_32 (.D(iae_setcount_1), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(iae_setcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_30 (.D(iae_setcount_3), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(iae_setcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(iae_setcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(iae_setcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(iae_setcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(iae_setcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(iae_setcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(iae_setcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(iae_clrcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(iae_clrcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_20 (.D(iae_clrcount_2), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_clrcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_19 (.D(iae_clrcount_3), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_clrcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(iae_clrcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(iae_clrcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(iae_clrcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(iae_clrcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(iae_clrcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(iae_clrcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(iae_clrcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_clrcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_11 (.D(ae_d), .CK(RdClock), .PD(rRst), .Q(ae))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_10 (.D(iaf_setcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(iaf_setcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(iaf_setcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_7 (.D(iaf_setcount_3), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_6 (.D(iaf_setcount_4), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(iaf_setcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(iaf_setcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(iaf_setcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(iaf_setcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(iaf_setcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_set), .CK(WrClock), .CD(Reset), .Q(AlmostFull))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1));

    defparam w_gctr_2.INJECT1_1 = "NO" ;
    defparam w_gctr_2.INJECT1_0 = "NO" ;
    defparam w_gctr_2.INIT1 =  16'h66AA ;
    defparam w_gctr_2.INIT0 =  16'h66AA ;
    CCU2C w_gctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2));

    defparam w_gctr_3.INJECT1_1 = "NO" ;
    defparam w_gctr_3.INJECT1_0 = "NO" ;
    defparam w_gctr_3.INIT1 =  16'h66AA ;
    defparam w_gctr_3.INIT0 =  16'h66AA ;
    CCU2C w_gctr_3 (.A0(wcount_6), .A1(wcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(iwcount_6), .S1(iwcount_7), .COUT(co3));

    defparam w_gctr_4.INJECT1_1 = "NO" ;
    defparam w_gctr_4.INJECT1_0 = "NO" ;
    defparam w_gctr_4.INIT1 =  16'h66AA ;
    defparam w_gctr_4.INIT0 =  16'h66AA ;
    CCU2C w_gctr_4 (.A0(wcount_8), .A1(wcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3), .S0(iwcount_8), .S1(iwcount_9), .COUT(co4));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2_1));

    defparam r_gctr_3.INJECT1_1 = "NO" ;
    defparam r_gctr_3.INJECT1_0 = "NO" ;
    defparam r_gctr_3.INIT1 =  16'h66AA ;
    defparam r_gctr_3.INIT0 =  16'h66AA ;
    CCU2C r_gctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(ircount_6), .S1(ircount_7), .COUT(co3_1));

    defparam r_gctr_4.INJECT1_1 = "NO" ;
    defparam r_gctr_4.INJECT1_0 = "NO" ;
    defparam r_gctr_4.INIT1 =  16'h66AA ;
    defparam r_gctr_4.INIT0 =  16'h66AA ;
    CCU2C r_gctr_4 (.A0(rcount_8), .A1(rcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_1), .S0(ircount_8), .S1(ircount_9), .COUT(co4_1));

    defparam r_gctr_5.INJECT1_1 = "NO" ;
    defparam r_gctr_5.INJECT1_0 = "NO" ;
    defparam r_gctr_5.INIT1 =  16'h66AA ;
    defparam r_gctr_5.INIT0 =  16'h66AA ;
    CCU2C r_gctr_5 (.A0(rcount_10), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_1), .S0(ircount_10), .S1(), .COUT(co5));

    defparam precin_inst364.INJECT1_1 = "NO" ;
    defparam precin_inst364.INJECT1_0 = "NO" ;
    defparam precin_inst364.INIT1 =  16'h0000 ;
    defparam precin_inst364.INIT0 =  16'h0000 ;
    CCU2C precin_inst364 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin));

    defparam wfill_0.INJECT1_1 = "NO" ;
    defparam wfill_0.INJECT1_0 = "NO" ;
    defparam wfill_0.INIT1 =  16'h99AA ;
    defparam wfill_0.INIT0 =  16'h99AA ;
    CCU2C wfill_0 (.A0(scuba_vhi), .A1(wptr_0), .B0(scuba_vlo), .B1(rcount_w1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin), .S0(), .S1(wfill_sub_0), .COUT(co0_2));

    defparam wfill_1.INJECT1_1 = "NO" ;
    defparam wfill_1.INJECT1_0 = "NO" ;
    defparam wfill_1.INIT1 =  16'h99AA ;
    defparam wfill_1.INIT0 =  16'h99AA ;
    CCU2C wfill_1 (.A0(wptr_1), .A1(wptr_2), .B0(rcount_w2), .B1(rcount_w3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(wfill_sub_1), .S1(wfill_sub_2), .COUT(co1_2));

    defparam wfill_2.INJECT1_1 = "NO" ;
    defparam wfill_2.INJECT1_0 = "NO" ;
    defparam wfill_2.INIT1 =  16'h99AA ;
    defparam wfill_2.INIT0 =  16'h99AA ;
    CCU2C wfill_2 (.A0(wptr_3), .A1(wptr_4), .B0(rcount_w4), .B1(rcount_w5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(wfill_sub_3), .S1(wfill_sub_4), .COUT(co2_2));

    defparam wfill_3.INJECT1_1 = "NO" ;
    defparam wfill_3.INJECT1_0 = "NO" ;
    defparam wfill_3.INIT1 =  16'h99AA ;
    defparam wfill_3.INIT0 =  16'h99AA ;
    CCU2C wfill_3 (.A0(wptr_5), .A1(wptr_6), .B0(rcount_w6), .B1(r_g2b_xor_cluster_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_2), .S0(wfill_sub_5), .S1(wfill_sub_6), .COUT(co3_2));

    defparam wfill_4.INJECT1_1 = "NO" ;
    defparam wfill_4.INJECT1_0 = "NO" ;
    defparam wfill_4.INIT1 =  16'h99AA ;
    defparam wfill_4.INIT0 =  16'h99AA ;
    CCU2C wfill_4 (.A0(wptr_7), .A1(wptr_8), .B0(rcount_w8), .B1(rcount_w9), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_2), .S0(wfill_sub_7), .S1(wfill_sub_8), .COUT(co4_2));

    defparam wfill_5.INJECT1_1 = "NO" ;
    defparam wfill_5.INJECT1_0 = "NO" ;
    defparam wfill_5.INIT1 =  16'h99AA ;
    defparam wfill_5.INIT0 =  16'h99AA ;
    CCU2C wfill_5 (.A0(wfill_sub_msb), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_2), .S0(wfill_sub_9), .S1(), .COUT());

    defparam precin_inst382.INJECT1_1 = "NO" ;
    defparam precin_inst382.INJECT1_0 = "NO" ;
    defparam precin_inst382.INIT1 =  16'h0000 ;
    defparam precin_inst382.INIT0 =  16'h0000 ;
    CCU2C precin_inst382 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin_1));

    defparam rfill_0.INJECT1_1 = "NO" ;
    defparam rfill_0.INJECT1_0 = "NO" ;
    defparam rfill_0.INIT1 =  16'h99AA ;
    defparam rfill_0.INIT0 =  16'h99AA ;
    CCU2C rfill_0 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), .B1(rptr_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin_1), .S0(), .S1(rfill_sub_0), .COUT(co0_3));

    defparam rfill_1.INJECT1_1 = "NO" ;
    defparam rfill_1.INJECT1_0 = "NO" ;
    defparam rfill_1.INIT1 =  16'h99AA ;
    defparam rfill_1.INIT0 =  16'h99AA ;
    CCU2C rfill_1 (.A0(wcount_r0), .A1(wcount_r1), .B0(rptr_1), .B1(rptr_2), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(rfill_sub_1), .S1(rfill_sub_2), .COUT(co1_3));

    defparam rfill_2.INJECT1_1 = "NO" ;
    defparam rfill_2.INJECT1_0 = "NO" ;
    defparam rfill_2.INIT1 =  16'h99AA ;
    defparam rfill_2.INIT0 =  16'h99AA ;
    CCU2C rfill_2 (.A0(wcount_r2), .A1(wcount_r3), .B0(rptr_3), .B1(rptr_4), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(rfill_sub_3), .S1(rfill_sub_4), .COUT(co2_3));

    defparam rfill_3.INJECT1_1 = "NO" ;
    defparam rfill_3.INJECT1_0 = "NO" ;
    defparam rfill_3.INIT1 =  16'h99AA ;
    defparam rfill_3.INIT0 =  16'h99AA ;
    CCU2C rfill_3 (.A0(wcount_r4), .A1(wcount_r5), .B0(rptr_5), .B1(rptr_6), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_3), .S0(rfill_sub_5), .S1(rfill_sub_6), .COUT(co3_3));

    defparam rfill_4.INJECT1_1 = "NO" ;
    defparam rfill_4.INJECT1_0 = "NO" ;
    defparam rfill_4.INIT1 =  16'h99AA ;
    defparam rfill_4.INIT0 =  16'h99AA ;
    CCU2C rfill_4 (.A0(w_g2b_xor_cluster_0), .A1(wcount_r7), .B0(rptr_7), 
        .B1(rptr_8), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_3), .S0(rfill_sub_7), .S1(rfill_sub_8), .COUT(co4_3));

    defparam rfill_5.INJECT1_1 = "NO" ;
    defparam rfill_5.INJECT1_0 = "NO" ;
    defparam rfill_5.INIT1 =  16'h99AA ;
    defparam rfill_5.INIT0 =  16'h99AA ;
    CCU2C rfill_5 (.A0(wcount_r8), .A1(rfill_sub_msb), .B0(rptr_9), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_3), .S0(rfill_sub_9), .S1(rfill_sub_10), .COUT(co5_1));

    defparam rfilld.INJECT1_1 = "NO" ;
    defparam rfilld.INJECT1_0 = "NO" ;
    defparam rfilld.INIT1 =  16'h66AA ;
    defparam rfilld.INIT0 =  16'h66AA ;
    CCU2C rfilld (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_1), .S0(co5_1d), .S1(), .COUT());

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(wcount_r0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_4));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r1), .B1(wcount_r2), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_4), .S0(), .S1(), .COUT(co1_4));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r3), .B1(wcount_r4), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_4), .S0(), .S1(), .COUT(co2_4));

    defparam empty_cmp_3.INJECT1_1 = "NO" ;
    defparam empty_cmp_3.INJECT1_0 = "NO" ;
    defparam empty_cmp_3.INIT1 =  16'h99AA ;
    defparam empty_cmp_3.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_3 (.A0(rcount_6), .A1(rcount_7), .B0(wcount_r5), .B1(w_g2b_xor_cluster_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_4), .S0(), .S1(), .COUT(co3_4));

    defparam empty_cmp_4.INJECT1_1 = "NO" ;
    defparam empty_cmp_4.INJECT1_0 = "NO" ;
    defparam empty_cmp_4.INIT1 =  16'h99AA ;
    defparam empty_cmp_4.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_4 (.A0(rcount_8), .A1(rcount_9), .B0(wcount_r7), .B1(wcount_r8), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_4), .S0(), .S1(), .COUT(co4_4));

    defparam empty_cmp_5.INJECT1_1 = "NO" ;
    defparam empty_cmp_5.INJECT1_0 = "NO" ;
    defparam empty_cmp_5.INIT1 =  16'h99AA ;
    defparam empty_cmp_5.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_5 (.A0(empty_cmp_set), .A1(scuba_vlo), .B0(empty_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_4), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w1), .B1(rcount_w2), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_5));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w3), .B1(rcount_w4), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_5), .S0(), .S1(), .COUT(co1_5));

    defparam full_cmp_2.INJECT1_1 = "NO" ;
    defparam full_cmp_2.INJECT1_0 = "NO" ;
    defparam full_cmp_2.INIT1 =  16'h99AA ;
    defparam full_cmp_2.INIT0 =  16'h99AA ;
    CCU2C full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w5), .B1(rcount_w6), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_5), .S0(), .S1(), .COUT(co2_5));

    defparam full_cmp_3.INJECT1_1 = "NO" ;
    defparam full_cmp_3.INJECT1_0 = "NO" ;
    defparam full_cmp_3.INIT1 =  16'h99AA ;
    defparam full_cmp_3.INIT0 =  16'h99AA ;
    CCU2C full_cmp_3 (.A0(wcount_6), .A1(wcount_7), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w8), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_5), .S0(), .S1(), .COUT(co3_5));

    defparam full_cmp_4.INJECT1_1 = "NO" ;
    defparam full_cmp_4.INJECT1_0 = "NO" ;
    defparam full_cmp_4.INIT1 =  16'h99AA ;
    defparam full_cmp_4.INIT0 =  16'h99AA ;
    CCU2C full_cmp_4 (.A0(wcount_8), .A1(full_cmp_set), .B0(rcount_w9), 
        .B1(full_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_5), .S0(), .S1(), .COUT(full_d_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    defparam ae_set_ctr_cia.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_cia.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_cia.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(ae_set_ctr_ci));

    defparam ae_set_ctr_0.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_0.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_0.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_0.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_0 (.A0(ae_setcount_0), .A1(ae_setcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(ae_set_ctr_ci), .S0(iae_setcount_0), .S1(iae_setcount_1), 
        .COUT(co0_6));

    defparam ae_set_ctr_1.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_1.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_1.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_1.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_1 (.A0(ae_setcount_2), .A1(ae_setcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_6), .S0(iae_setcount_2), .S1(iae_setcount_3), 
        .COUT(co1_6));

    defparam ae_set_ctr_2.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_2.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_2.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_2.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_2 (.A0(ae_setcount_4), .A1(ae_setcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_6), .S0(iae_setcount_4), .S1(iae_setcount_5), 
        .COUT(co2_6));

    defparam ae_set_ctr_3.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_3.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_3.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_3.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_3 (.A0(ae_setcount_6), .A1(ae_setcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_6), .S0(iae_setcount_6), .S1(iae_setcount_7), 
        .COUT(co3_6));

    defparam ae_set_ctr_4.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_4.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_4.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_4.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_4 (.A0(ae_setcount_8), .A1(ae_setcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_6), .S0(iae_setcount_8), .S1(iae_setcount_9), 
        .COUT(co4_5));

    defparam ae_set_ctr_5.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_5.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_5.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_5.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_5 (.A0(ae_setcount_10), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_5), .S0(iae_setcount_10), .S1(), .COUT(co5_2));

    defparam ae_set_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam ae_set_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C ae_set_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_2));

    defparam ae_set_cmp_0.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_0.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_0.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_0.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_0 (.A0(ae_setcount_0), .A1(ae_setcount_1), .B0(scuba_vlo), 
        .B1(wcount_r0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_2), .S0(), .S1(), .COUT(co0_7));

    defparam ae_set_cmp_1.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_1.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_1.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_1.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_1 (.A0(ae_setcount_2), .A1(ae_setcount_3), .B0(wcount_r1), 
        .B1(wcount_r2), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_7), .S0(), .S1(), .COUT(co1_7));

    defparam ae_set_cmp_2.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_2.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_2.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_2.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_2 (.A0(ae_setcount_4), .A1(ae_setcount_5), .B0(wcount_r3), 
        .B1(wcount_r4), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_7), .S0(), .S1(), .COUT(co2_7));

    defparam ae_set_cmp_3.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_3.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_3.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_3.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_3 (.A0(ae_setcount_6), .A1(ae_setcount_7), .B0(wcount_r5), 
        .B1(w_g2b_xor_cluster_0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_7), .S0(), .S1(), .COUT(co3_7));

    defparam ae_set_cmp_4.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_4.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_4.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_4.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_4 (.A0(ae_setcount_8), .A1(ae_setcount_9), .B0(wcount_r7), 
        .B1(wcount_r8), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_7), .S0(), .S1(), .COUT(co4_6));

    defparam ae_set_cmp_5.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_5.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_5.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_5.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_5 (.A0(ae_set_cmp_set), .A1(scuba_vlo), .B0(ae_set_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_6), .S0(), .S1(), .COUT(ae_set_d_c));

    defparam a2.INJECT1_1 = "NO" ;
    defparam a2.INJECT1_0 = "NO" ;
    defparam a2.INIT1 =  16'h66AA ;
    defparam a2.INIT0 =  16'h66AA ;
    CCU2C a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(ae_set_d_c), .S0(ae_set_d), .S1(), .COUT());

    defparam ae_clr_ctr_cia.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_cia.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_cia.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(ae_clr_ctr_ci));

    defparam ae_clr_ctr_0.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_0.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_0.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_0.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_0 (.A0(ae_clrcount_0), .A1(ae_clrcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(ae_clr_ctr_ci), .S0(iae_clrcount_0), .S1(iae_clrcount_1), 
        .COUT(co0_8));

    defparam ae_clr_ctr_1.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_1.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_1.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_1.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_1 (.A0(ae_clrcount_2), .A1(ae_clrcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_8), .S0(iae_clrcount_2), .S1(iae_clrcount_3), 
        .COUT(co1_8));

    defparam ae_clr_ctr_2.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_2.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_2.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_2.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_2 (.A0(ae_clrcount_4), .A1(ae_clrcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_8), .S0(iae_clrcount_4), .S1(iae_clrcount_5), 
        .COUT(co2_8));

    defparam ae_clr_ctr_3.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_3.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_3.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_3.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_3 (.A0(ae_clrcount_6), .A1(ae_clrcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_8), .S0(iae_clrcount_6), .S1(iae_clrcount_7), 
        .COUT(co3_8));

    defparam ae_clr_ctr_4.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_4.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_4.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_4.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_4 (.A0(ae_clrcount_8), .A1(ae_clrcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_8), .S0(iae_clrcount_8), .S1(iae_clrcount_9), 
        .COUT(co4_7));

    defparam ae_clr_ctr_5.INJECT1_1 = "NO" ;
    defparam ae_clr_ctr_5.INJECT1_0 = "NO" ;
    defparam ae_clr_ctr_5.INIT1 =  16'h66AA ;
    defparam ae_clr_ctr_5.INIT0 =  16'h66AA ;
    CCU2C ae_clr_ctr_5 (.A0(ae_clrcount_10), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_7), .S0(iae_clrcount_10), .S1(), .COUT(co5_3));

    defparam ae_clr_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam ae_clr_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C ae_clr_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_3));

    defparam ae_clr_cmp_0.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_0.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_0.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_0.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_0 (.A0(ae_clrcount_0), .A1(ae_clrcount_1), .B0(scuba_vlo), 
        .B1(wcount_r0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_3), .S0(), .S1(), .COUT(co0_9));

    defparam ae_clr_cmp_1.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_1.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_1.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_1.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_1 (.A0(ae_clrcount_2), .A1(ae_clrcount_3), .B0(wcount_r1), 
        .B1(wcount_r2), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_9), .S0(), .S1(), .COUT(co1_9));

    defparam ae_clr_cmp_2.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_2.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_2.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_2.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_2 (.A0(ae_clrcount_4), .A1(ae_clrcount_5), .B0(wcount_r3), 
        .B1(wcount_r4), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_9), .S0(), .S1(), .COUT(co2_9));

    defparam ae_clr_cmp_3.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_3.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_3.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_3.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_3 (.A0(ae_clrcount_6), .A1(ae_clrcount_7), .B0(wcount_r5), 
        .B1(w_g2b_xor_cluster_0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_9), .S0(), .S1(), .COUT(co3_9));

    defparam ae_clr_cmp_4.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_4.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_4.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_4.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_4 (.A0(ae_clrcount_8), .A1(ae_clrcount_9), .B0(wcount_r7), 
        .B1(wcount_r8), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_9), .S0(), .S1(), .COUT(co4_8));

    defparam ae_clr_cmp_5.INJECT1_1 = "NO" ;
    defparam ae_clr_cmp_5.INJECT1_0 = "NO" ;
    defparam ae_clr_cmp_5.INIT1 =  16'h99AA ;
    defparam ae_clr_cmp_5.INIT0 =  16'h99AA ;
    CCU2C ae_clr_cmp_5 (.A0(ae_clr_cmp_set), .A1(scuba_vlo), .B0(ae_clr_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_8), .S0(), .S1(), .COUT(ae_clr_d_c));

    defparam a3.INJECT1_1 = "NO" ;
    defparam a3.INJECT1_0 = "NO" ;
    defparam a3.INIT1 =  16'h66AA ;
    defparam a3.INIT0 =  16'h66AA ;
    CCU2C a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(ae_clr_d_c), .S0(ae_clr_d), .S1(), .COUT());

    defparam af_set_ctr_cia.INJECT1_1 = "NO" ;
    defparam af_set_ctr_cia.INJECT1_0 = "NO" ;
    defparam af_set_ctr_cia.INIT1 =  16'h66AA ;
    defparam af_set_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(af_set_ctr_ci));

    defparam af_set_ctr_0.INJECT1_1 = "NO" ;
    defparam af_set_ctr_0.INJECT1_0 = "NO" ;
    defparam af_set_ctr_0.INIT1 =  16'h66AA ;
    defparam af_set_ctr_0.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(af_set_ctr_ci), .S0(iaf_setcount_0), .S1(iaf_setcount_1), 
        .COUT(co0_10));

    defparam af_set_ctr_1.INJECT1_1 = "NO" ;
    defparam af_set_ctr_1.INJECT1_0 = "NO" ;
    defparam af_set_ctr_1.INIT1 =  16'h66AA ;
    defparam af_set_ctr_1.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_10), .S0(iaf_setcount_2), .S1(iaf_setcount_3), 
        .COUT(co1_10));

    defparam af_set_ctr_2.INJECT1_1 = "NO" ;
    defparam af_set_ctr_2.INJECT1_0 = "NO" ;
    defparam af_set_ctr_2.INIT1 =  16'h66AA ;
    defparam af_set_ctr_2.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_10), .S0(iaf_setcount_4), .S1(iaf_setcount_5), 
        .COUT(co2_10));

    defparam af_set_ctr_3.INJECT1_1 = "NO" ;
    defparam af_set_ctr_3.INJECT1_0 = "NO" ;
    defparam af_set_ctr_3.INIT1 =  16'h66AA ;
    defparam af_set_ctr_3.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_10), .S0(iaf_setcount_6), .S1(iaf_setcount_7), 
        .COUT(co3_10));

    defparam af_set_ctr_4.INJECT1_1 = "NO" ;
    defparam af_set_ctr_4.INJECT1_0 = "NO" ;
    defparam af_set_ctr_4.INIT1 =  16'h66AA ;
    defparam af_set_ctr_4.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_4 (.A0(af_setcount_8), .A1(af_setcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_10), .S0(iaf_setcount_8), .S1(iaf_setcount_9), 
        .COUT(co4_9));

    defparam af_set_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam af_set_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam af_set_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam af_set_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C af_set_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), 
        .B1(wren_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_4));

    defparam af_set_cmp_0.INJECT1_1 = "NO" ;
    defparam af_set_cmp_0.INJECT1_0 = "NO" ;
    defparam af_set_cmp_0.INIT1 =  16'h99AA ;
    defparam af_set_cmp_0.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(rcount_w1), 
        .B1(rcount_w2), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_4), .S0(), .S1(), .COUT(co0_11));

    defparam af_set_cmp_1.INJECT1_1 = "NO" ;
    defparam af_set_cmp_1.INJECT1_0 = "NO" ;
    defparam af_set_cmp_1.INIT1 =  16'h99AA ;
    defparam af_set_cmp_1.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(rcount_w3), 
        .B1(rcount_w4), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_11), .S0(), .S1(), .COUT(co1_11));

    defparam af_set_cmp_2.INJECT1_1 = "NO" ;
    defparam af_set_cmp_2.INJECT1_0 = "NO" ;
    defparam af_set_cmp_2.INIT1 =  16'h99AA ;
    defparam af_set_cmp_2.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(rcount_w5), 
        .B1(rcount_w6), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_11), .S0(), .S1(), .COUT(co2_11));

    defparam af_set_cmp_3.INJECT1_1 = "NO" ;
    defparam af_set_cmp_3.INJECT1_0 = "NO" ;
    defparam af_set_cmp_3.INIT1 =  16'h99AA ;
    defparam af_set_cmp_3.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w8), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_11), .S0(), .S1(), .COUT(co3_11));

    defparam af_set_cmp_4.INJECT1_1 = "NO" ;
    defparam af_set_cmp_4.INJECT1_0 = "NO" ;
    defparam af_set_cmp_4.INIT1 =  16'h99AA ;
    defparam af_set_cmp_4.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_4 (.A0(af_setcount_8), .A1(af_set_cmp_set), .B0(rcount_w9), 
        .B1(af_set_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_11), .S0(), .S1(), .COUT(af_set_c));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a4.INJECT1_1 = "NO" ;
    defparam a4.INJECT1_0 = "NO" ;
    defparam a4.INIT1 =  16'h66AA ;
    defparam a4.INIT0 =  16'h66AA ;
    CCU2C a4 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(af_set_c), .S0(af_set), .S1(), .COUT());

    assign Empty = empty_i;
    assign Full = full_i;
    assign AlmostEmpty = ae;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_1 MEM_LPC_FILE slfifo_fifo.lpc
    // exemplar attribute pdp_ram_0_0_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_0 MEM_LPC_FILE slfifo_fifo.lpc
    // exemplar attribute pdp_ram_0_1_0 MEM_INIT_FILE 
    // exemplar attribute FF_161 GSR ENABLED
    // exemplar attribute FF_160 GSR ENABLED
    // exemplar attribute FF_159 GSR ENABLED
    // exemplar attribute FF_158 GSR ENABLED
    // exemplar attribute FF_157 GSR ENABLED
    // exemplar attribute FF_156 GSR ENABLED
    // exemplar attribute FF_155 GSR ENABLED
    // exemplar attribute FF_154 GSR ENABLED
    // exemplar attribute FF_153 GSR ENABLED
    // exemplar attribute FF_152 GSR ENABLED
    // exemplar attribute FF_151 GSR ENABLED
    // exemplar attribute FF_150 GSR ENABLED
    // exemplar attribute FF_149 GSR ENABLED
    // exemplar attribute FF_148 GSR ENABLED
    // exemplar attribute FF_147 GSR ENABLED
    // exemplar attribute FF_146 GSR ENABLED
    // exemplar attribute FF_145 GSR ENABLED
    // exemplar attribute FF_144 GSR ENABLED
    // exemplar attribute FF_143 GSR ENABLED
    // exemplar attribute FF_142 GSR ENABLED
    // exemplar attribute FF_141 GSR ENABLED
    // exemplar attribute FF_140 GSR ENABLED
    // exemplar attribute FF_139 GSR ENABLED
    // exemplar attribute FF_138 GSR ENABLED
    // exemplar attribute FF_137 GSR ENABLED
    // exemplar attribute FF_136 GSR ENABLED
    // exemplar attribute FF_135 GSR ENABLED
    // exemplar attribute FF_134 GSR ENABLED
    // exemplar attribute FF_133 GSR ENABLED
    // exemplar attribute FF_132 GSR ENABLED
    // exemplar attribute FF_131 GSR ENABLED
    // exemplar attribute FF_130 GSR ENABLED
    // exemplar attribute FF_129 GSR ENABLED
    // exemplar attribute FF_128 GSR ENABLED
    // exemplar attribute FF_127 GSR ENABLED
    // exemplar attribute FF_126 GSR ENABLED
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
