/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* Fri Jan 08 13:28:29 2021 */

/* parameterized module instance */
slfifo_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), .Empty( ), 
    .Full( ), .AlmostEmpty( ), .AlmostFull( ));
