/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Fri Apr 02 13:51:08 2021 */

/* parameterized module instance */
pll_clk __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
