/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_in -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type iol -mode Receive -io_type LVCMOS18 -width 16 -freq_in 150 -gear 2 -del 128 -fdc F:/cypress_prj/FTP/HDMI_RX_FPGA_design_FULLHD/PAR/hdmi_in/ddr_in/ddr_in.fdc  */
/* Fri Jan 08 13:29:39 2021 */


`timescale 1 ns / 1 ps
module ddr_in (clkin, reset, sclk, datain, q)/* synthesis NGD_DRC_MASK=1 */;
    input wire clkin;
    input wire reset;
    input wire [15:0] datain;
    output wire sclk;
    output wire [31:0] q;

    wire buf_clkin;
    wire qb15;
    wire qa15;
    wire qb14;
    wire qa14;
    wire qb13;
    wire qa13;
    wire qb12;
    wire qa12;
    wire qb11;
    wire qa11;
    wire qb10;
    wire qa10;
    wire qb9;
    wire qa9;
    wire qb8;
    wire qa8;
    wire qb7;
    wire qa7;
    wire qb6;
    wire qa6;
    wire qb5;
    wire qa5;
    wire qb4;
    wire qa4;
    wire qb3;
    wire qa3;
    wire qb2;
    wire qa2;
    wire qb1;
    wire qa1;
    wire qb0;
    wire qa0;
    wire sclk_t;
    wire dataini_t15;
    wire dataini_t14;
    wire dataini_t13;
    wire dataini_t12;
    wire dataini_t11;
    wire dataini_t10;
    wire dataini_t9;
    wire dataini_t8;
    wire dataini_t7;
    wire dataini_t6;
    wire dataini_t5;
    wire dataini_t4;
    wire dataini_t3;
    wire dataini_t2;
    wire dataini_t1;
    wire dataini_t0;
    wire buf_dataini15;
    wire buf_dataini14;
    wire buf_dataini13;
    wire buf_dataini12;
    wire buf_dataini11;
    wire buf_dataini10;
    wire buf_dataini9;
    wire buf_dataini8;
    wire buf_dataini7;
    wire buf_dataini6;
    wire buf_dataini5;
    wire buf_dataini4;
    wire buf_dataini3;
    wire buf_dataini2;
    wire buf_dataini1;
    wire buf_dataini0;

    IB Inst3_IB (.I(clkin), .O(buf_clkin))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IDDRX1F Inst2_IDDRX1F15 (.D(dataini_t15), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa15), .Q1(qb15));

    IDDRX1F Inst2_IDDRX1F14 (.D(dataini_t14), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa14), .Q1(qb14));

    IDDRX1F Inst2_IDDRX1F13 (.D(dataini_t13), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa13), .Q1(qb13));

    IDDRX1F Inst2_IDDRX1F12 (.D(dataini_t12), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa12), .Q1(qb12));

    IDDRX1F Inst2_IDDRX1F11 (.D(dataini_t11), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa11), .Q1(qb11));

    IDDRX1F Inst2_IDDRX1F10 (.D(dataini_t10), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa10), .Q1(qb10));

    IDDRX1F Inst2_IDDRX1F9 (.D(dataini_t9), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa9), .Q1(qb9));

    IDDRX1F Inst2_IDDRX1F8 (.D(dataini_t8), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa8), .Q1(qb8));

    IDDRX1F Inst2_IDDRX1F7 (.D(dataini_t7), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa7), .Q1(qb7));

    IDDRX1F Inst2_IDDRX1F6 (.D(dataini_t6), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa6), .Q1(qb6));

    IDDRX1F Inst2_IDDRX1F5 (.D(dataini_t5), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa5), .Q1(qb5));

    IDDRX1F Inst2_IDDRX1F4 (.D(dataini_t4), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa4), .Q1(qb4));

    IDDRX1F Inst2_IDDRX1F3 (.D(dataini_t3), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa3), .Q1(qb3));

    IDDRX1F Inst2_IDDRX1F2 (.D(dataini_t2), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa2), .Q1(qb2));

    IDDRX1F Inst2_IDDRX1F1 (.D(dataini_t1), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa1), .Q1(qb1));

    IDDRX1F Inst2_IDDRX1F0 (.D(dataini_t0), .SCLK(sclk_t), .RST(reset), 
        .Q0(qa0), .Q1(qb0));

    defparam udel_dataini15.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini15 (.A(buf_dataini15), .Z(dataini_t15));

    defparam udel_dataini14.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini14 (.A(buf_dataini14), .Z(dataini_t14));

    defparam udel_dataini13.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini13 (.A(buf_dataini13), .Z(dataini_t13));

    defparam udel_dataini12.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini12 (.A(buf_dataini12), .Z(dataini_t12));

    defparam udel_dataini11.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini11 (.A(buf_dataini11), .Z(dataini_t11));

    defparam udel_dataini10.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini10 (.A(buf_dataini10), .Z(dataini_t10));

    defparam udel_dataini9.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini9 (.A(buf_dataini9), .Z(dataini_t9));

    defparam udel_dataini8.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini8 (.A(buf_dataini8), .Z(dataini_t8));

    defparam udel_dataini7.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini7 (.A(buf_dataini7), .Z(dataini_t7));

    defparam udel_dataini6.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini6 (.A(buf_dataini6), .Z(dataini_t6));

    defparam udel_dataini5.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini5 (.A(buf_dataini5), .Z(dataini_t5));

    defparam udel_dataini4.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini4 (.A(buf_dataini4), .Z(dataini_t4));

    defparam udel_dataini3.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini3 (.A(buf_dataini3), .Z(dataini_t3));

    defparam udel_dataini2.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini2 (.A(buf_dataini2), .Z(dataini_t2));

    defparam udel_dataini1.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini1 (.A(buf_dataini1), .Z(dataini_t1));

    defparam udel_dataini0.DEL_MODE = "SCLK_CENTERED" ;
    DELAYG udel_dataini0 (.A(buf_dataini0), .Z(dataini_t0));

    IB Inst1_IB15 (.I(datain[15]), .O(buf_dataini15))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB14 (.I(datain[14]), .O(buf_dataini14))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB13 (.I(datain[13]), .O(buf_dataini13))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB12 (.I(datain[12]), .O(buf_dataini12))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB11 (.I(datain[11]), .O(buf_dataini11))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB10 (.I(datain[10]), .O(buf_dataini10))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB9 (.I(datain[9]), .O(buf_dataini9))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB8 (.I(datain[8]), .O(buf_dataini8))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB7 (.I(datain[7]), .O(buf_dataini7))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB6 (.I(datain[6]), .O(buf_dataini6))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB5 (.I(datain[5]), .O(buf_dataini5))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB4 (.I(datain[4]), .O(buf_dataini4))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB3 (.I(datain[3]), .O(buf_dataini3))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB2 (.I(datain[2]), .O(buf_dataini2))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB1 (.I(datain[1]), .O(buf_dataini1))
             /* synthesis IO_TYPE="LVCMOS18" */;

    IB Inst1_IB0 (.I(datain[0]), .O(buf_dataini0))
             /* synthesis IO_TYPE="LVCMOS18" */;

    assign sclk = sclk_t;
    assign q[31] = qb15;
    assign q[30] = qb14;
    assign q[29] = qb13;
    assign q[28] = qb12;
    assign q[27] = qb11;
    assign q[26] = qb10;
    assign q[25] = qb9;
    assign q[24] = qb8;
    assign q[23] = qb7;
    assign q[22] = qb6;
    assign q[21] = qb5;
    assign q[20] = qb4;
    assign q[19] = qb3;
    assign q[18] = qb2;
    assign q[17] = qb1;
    assign q[16] = qb0;
    assign q[15] = qa15;
    assign q[14] = qa14;
    assign q[13] = qa13;
    assign q[12] = qa12;
    assign q[11] = qa11;
    assign q[10] = qa10;
    assign q[9] = qa9;
    assign q[8] = qa8;
    assign q[7] = qa7;
    assign q[6] = qa6;
    assign q[5] = qa5;
    assign q[4] = qa4;
    assign q[3] = qa3;
    assign q[2] = qa2;
    assign q[1] = qa1;
    assign q[0] = qa0;
    assign sclk_t = buf_clkin;


    // exemplar begin
    // exemplar attribute Inst3_IB IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB15 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB14 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB13 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB12 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB11 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB10 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB9 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB8 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB7 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB6 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB5 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB4 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB3 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB2 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB1 IO_TYPE LVCMOS18
    // exemplar attribute Inst1_IB0 IO_TYPE LVCMOS18
    // exemplar end

endmodule
