/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* Fri Jan 08 13:29:39 2021 */

/* parameterized module instance */
ddr_in __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
